# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab48995662bdfc54b54cbd24756d51f7eddda3dce3db2c35ffce0e372e10760a4b75e937c51c90152a65cad19ccb39cdc39244f9b1b0d7bfb5ea618218458d0d

test:
  secret_key_base: 1e461f7688c8360853e318d868b84712b33a63218f1952568cd758b7f806bfead77c58bc1fe998ab98e9e8a2478ea217a03d1b28b4f012f6e482c675ca16d6e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
